openapi: 3.0.0
info:
  version: 1.0.0
  title: MercadoLibre API
  description: API to access the MercadoLibre service in the Sysmika SDK. Provides a gateway to operations on the MercadoLibre platform
servers:
  - url: localhost:8000/
# Basic authentication
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    AccessToken:
      type: object
      properties:
        access_token:
          type: string
        user_id:
          type: integer
        refresh_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer

security:
  - BasicAuth: []

paths:
  /auth/access_token:
    get:
      description: Generates an access token on the MercadoLibre site.
      operationId: generate_access_token
      responses:
        '200':
          description: An AccessToken object is generated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessToken"
        '400':
          description: Missing requried header
          content:
            application/json:
              schema:
                type: string
        default:
          description: "Access token creation failed"
          content:
            application/json:
              schema:
                type: string
      parameters:
        - in: header
          name: tg_code
          required: true
          example: "{tg_code: TG-123456}"
          schema:
            type: string
          description: "Code generated by the MercadoLibre app on user authentication"
        - in: header
          name: redirect_url
          required: true
          example: "{redirect_url: http://sysmika.com.ar}"
          schema:
            type: string
          description: "Redirect URL specified on the user app on MercadoLibre"
        - in: header
          name: app_id
          required: true
          description: "Id of the MercadoLibre integration app. Obtainable  in developers.mercadolibre"
          example: "{app_id: APP-2134}"
          schema:
            type: string
        - in: header
          name: app_secret
          required: true
          description: "Secret Id of the MercadoLibre integration app. Obtainable  in developers.mercadolibre"
          example: "{app_secret: SG-20983}"
          schema:
            type: string