# Generated by Django 4.0 on 2022-01-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.AddField(
            model_name='user',
            name='app_id',
            field=models.CharField(default=-1, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='app_secret',
            field=models.CharField(default=-1, max_length=500),
        ),
    ]
