# Generated by Django 4.0.1 on 2022-01-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0005_user_app_token_user_refresh_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='app_token',
            new_name='access_token',
        ),
    ]
